merge changes from bug #2348

diff --git a/getjava b/getjava
--- a/getjava
+++ b/getjava
@@ -2,10 +2,6 @@
 
 # $Id: getjava 6644 2007-06-29 20:47:39Z jgehlbach $
 
-#
-# Get JAVA_HOME and derive PATH
-#
-
 if [ -z "$JAVA_HOME" ]; then
     for dir in /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun
     do
@@ -16,22 +12,9 @@ if [ -z "$JAVA_HOME" ]; then
     done
 
     if [ -z "$JAVA_HOME" ]; then
-        echo "You need to set a valid JAVA_HOME in /etc/default/$NAME" >&2
+        echo "Could not find the jvm, please set JAVA_HOME" >&2
         exit 1
     fi
 fi
-PATH=${JAVA_HOME}/bin:$PATH
 
-case "$1" in
-	"JAVA_HOME")
-		echo "$JAVA_HOME"
-		;;
-	"PATH")
-		echo "$PATH"
-		;;
-	*)
-		echo "You must specify either JAVA_HOME or PATH as the sole argument."
-		exit 1
-		;;
-esac
-
+echo "$JAVA_HOME"
